# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme: custom
defaultAppearance: dark
autoSwitchAppearance: true

enableSearch: true
enableCodeCopy: true

replyByEmail: false


mainSections:
  - docs
  - project
# robots: ""

disableImageOptimization: false
disableTextInHeader: false
# backgroundImageWidth: 1200

defaultBackgroundImage: img/card/turquoise-rust.webp # used as default for background images
# defaultFeaturedImage: "IMAGE.jpg" # used as default for featured images in all articles

highlightCurrentMenuArea: true
smartTOC: true
# smartTOCHideUnfocusedChildren: true

giteaDefaultServer: https://git.fsfe.org
forgejoDefaultServer: https://v8.next.forgejo.org


header:
  layout: fixed # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

footer:
  showMenu: true
  showCopyright: true
  showThemeAttribution: true
  showAppearanceSwitcher: true
  showScrollToTop: true


homepage:
  layout: custom # valid options: page, profile, hero, card, background, custom
  homepageImage: img/card/turquoise-wood.webp # used in: hero, and card
  showRecent: true
  showRecentItems: 10
  showMoreLink: false
  showMoreLinkDest: /
  cardView: true
  cardViewScreenWidth: false
  layoutBackgroundBlur: false # only used when layout equals background


article:
  showDate: true
  showViews: false
  showLikes: false
  showDateOnlyInArticle: false
  showDateUpdated: true
  showAuthor: true
#   showAuthorBottom: false
  showHero: true
  heroStyle: background # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur: true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace: true # only used when heroStyle equals background
  showBreadcrumbs: true
  showDraftLabel: true
  showEdit: true
  editURL: "https://github.com/2425-3ahitm-itp/02-projekte-helpr/edit/dev/hugo/content"
  editAppendPath: true
  seriesOpened: false
  showHeadingAnchors: true
  showPagination: true
  invertPagination: false
  showReadingTime: true
  showTableOfContents: true
#   showRelatedContent: false
#   relatedContentLimit: = 3
  showTaxonomies: true
  showAuthorsBadges: false
  showWordCount: true
  sharingLinks:
#     - linkedin
    - twitter
    - bluesky
    - mastodon
    - reddit
#     - pinterest
#     - facebook
    - email
#     - whatsapp
#     - telegram
  showZenMode: false


list:
  showHero: true
  heroStyle: background # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur: true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace: true # only used when heroStyle equals background
  showBreadcrumbs: true
  showSummary: false
  showViews: false
  showLikes: false
  showTableOfContents: false
  showCards: false
  orderByWeight: true
  groupByYear: true
  cardView: false
  cardViewScreenWidth: false
  constrainItemsWidth: false


sitemap:
  excludedKinds:
    - taxonomy
    - term


taxonomy:
  showTermCount: true
  showHero: true
  heroStyle: background # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs: true
  showViews: false
  showLikes: false
  showTableOfContents: true
  cardView: false


term:
  showHero: true
  heroStyle: background # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs: true
  showViews: false
  showLikes: false
  showTableOfContents: true
  groupByYear: false
  cardView: false
  cardViewScreenWidth: false

