services:
  frontend:
    container_name: www
    image: ghcr.io/mgnadlinger/music-voting-frontend:latest
    ports:
      - "4200:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      backend:
        condition: service_healthy
